ALTER TABLE paper_state
    ADD COLUMN IF NOT EXISTS cost_bases JSONB NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS consecutive_losses INT NOT NULL DEFAULT 0;

ALTER TABLE paper_fills
    ADD COLUMN IF NOT EXISTS cost_basis DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS realized_pnl DOUBLE PRECISION;
